### ISSUE TITLE
Allow installing via Homebrew

### ISSUE THREAD

**Issue by artemnovichkov** [GettEngineering/Prism#13]
Hello, guys! At first, thanks for the tool! It looks useful and solid, especially for syncing. BTW, I use [Zepcode](https://github.com/artemnovichkov/zepcode), Zeplin extension for Swift code snippets, but extensions have no logic for syncing. Anyway, I tried to install Prism with attached release, but have two errors
- `“prism-macOS.dms” cannot be opened because it is from an unidentified developer.`. Classic security error.
- `The contents of "prism-macOS.dms" cannot be extracted with The Unarchiver` after allowing to install the package.
It's not convenient to download and build Prism from sources, especially for new releases. Are you going to add Homebrew support?

**Comment by freak4pc** [comment]
Hey again @artemnovichkov :) Thanks foe the compliments! 

Indeed extensions are great but they don't offer a lot of flexibility. You can't run them as part of a CI pipeline, etc. 

You have some pretty good feedback, I think that:

1. I need to look into how to properly sign the CLI for Gatekeeper
2. I'm happy to check how to add Prism to Homebrew. If you wanna make a PR for that, I'm happy to accept it. 

Regardless, you can also use mint for installation which is quite nice (`brew install mint && mint install GettEngineeing/prism`)

Happy to hear your thoughts :)

**Comment by artemnovichkov** [comment]
Sorry for the long-time response!
1. Is it required to sign CLI tools? I have some, and they work w/o signing
2. I'm not a big master of Homebrew integration, but I'll try to do it. Should I add brew formula to the project repo?

BTW, it would be great to automate Homebrew releases with CI.

**Comment by freak4pc** [comment]
The trick with Homebrew is that it compiles it on the user's end so there's no need for signing if you're the one who builds from source (like with the `make install` in this repo). Distributing as a binary like I did will give you a waning because it's a binary distribution downloaded from an unknown souurce. 

I don't mind digging into this myself, I think this would be a good inspiration:

https://github.com/Homebrew/homebrew-core/blob/64749bb12994926a4af7971d1b249a137fde3e8b/Formula/swiftlint.rb#L19

https://github.com/realm/SwiftLint/blob/master/Makefile#L101-L103

**Comment by artemnovichkov** [comment]
In this case, why do you want to distribute binaries? To prevent compiling issues and doesn't depend on user's environment?

**Comment by freak4pc** [comment]
I'm not tied to that idea, I didn't think about it having issues with GateKeeper. I'd opt for supporting Homebrew and not distributing binaries at all. Between Homebrew, Mint, and `make install`, most users should be good to go

**Comment by freak4pc** [comment]
You can now install via Homebrew using `brew install GettEngineering/tap/prism`, README updated accordingly. Thanks !
