### ISSUE TITLE
Rounding of letter spacing

### ISSUE THREAD

**Issue by artemnovichkov** [GettEngineering/Prism#14]
Here is my text style in Zeplin:
<img width="631" alt="Screenshot 2020-03-12 at 12 48 39" src="https://user-images.githubusercontent.com/5051597/76494783-cfd90b00-645f-11ea-98af-3819fbc2787a.png">
Here is generated code for the style:
```swift
static let searchBarPlaceholder: TextStyle = {
        let style = TextStyle()
        style.font = .SFProText-Regular(ofSize: 17.0, weight: .semibold)
        style.kerning = -0.408
        style.color = .additional1d
        style.lineHeight = 22.0
        return style
}()
```
I guess there are some hidden rules of rounding. I use [this logic](https://github.com/artemnovichkov/stylin/blob/250cd1f17ba5b4ffc8270c7dd3e1d62215973c8b/src/helpers.js#L6) for code generation. What do you think? Should Prism update digit values from Zeplin?>

**Comment by freak4pc** [comment]
Hey! Sorry, I guess I had some issues getting notified on issues :) Here now. 

Can you share the prism template you're using? 
I imagine 0.4 is the raw data from Zeplin, I think we can probably allow up to two digits of precision plus some rounding, e.g. 0.408 would be 0.4, 0.488 will be 0.49, 0.498 will be 0.5, etc.

WDYT ?

**Comment by artemnovichkov** [comment]
Here is my template, nothing special:
```
import UIKit
import Texstyle

extension TextStyle {

    {{% FOR textStyle %}}
    static let {{%textStyle.identity.camelcase%}}: TextStyle = {
        let style = TextStyle()
        style.font = .{{%textStyle.fontName%}}(ofSize: {{%textStyle.fontSize%}}, weight: .semibold)
        {{% IF textStyle.letterSpacing %}}style.kerning = {{%textStyle.letterSpacing%}}{{% ENDIF %}}
        style.color = .{{%textStyle.color.identity.camelcase%}}
        {{% IF textStyle.alignment %}}style.alignment = .{{%textStyle.alignment|replace(justify,justified)%}}{{% ENDIF %}}
        {{% IF textStyle.lineHeight %}}style.lineHeight = {{%textStyle.lineHeight%}}{{% ENDIF %}}
        return style
    }()

    {{% END textStyle %}}
}
```
About rounding - I guess it's a good addition and best place for first PR :)

**Comment by freak4pc** [comment]
Thanks! Looks good :) Glad you found it easy to use. 

About the rounding, yeah - that would be a great PR and quick to do. Would you want to take care of it @artemnovichkov ?

We would probably not want to change the raw model, but just round it when resolving the token: 

https://github.com/GettEngineering/Prism/blob/28fb0b2acf6c8f7d2fbeaeaaef9642d003c6a3d4/Sources/PrismCore/TemplateParser/TemplateParser%2BToken.swift#L149-L152

If you do this, be sure to add some tests around this :) **TemplateParserSpec.swift** should be the right place for that. 

Let me know if you need any help! Or, if you're not free, I'm happy to do it myself.

**Comment by artemnovichkov** [comment]
I'll do it, thanks for the additional information!

**Comment by freak4pc** [comment]
Sure! By the way, I think the best strategy would be something like

```swift
(spacing * 100).rounded(.toNearestOrEven) / spacing
```

But feel free to go with any strategy you like best :)
