### ISSUE TITLE
FontName SnakeCase for Android compatibility

### ISSUE THREAD

**Issue by bvescovi-orangeloops** [GettEngineering/Prism#20]
Hi @freak4pc!

Nice work so far!
Just found something that's annoying me
At the Examples/Android folder for textStyles it's using:

`<item name="android:fontFamily">@font/{{% textStyle.fontName|lowercase|replace(-,_) %}}</item>` 
On that part it's using the transformation `lowercase` and `replace` but when I run the `prism generate` I get an error `❌ Error: There is no transformation called 'replace(-,_) '` or `lowercase` if I delete that transformation.
Is there something I'm missing? Do you think it make sense to add the snakecase token for this property also?
Cheers

**Comment by bvescovi-orangeloops** [comment]
I did take a look at the code and found that was actually handled.
I've found a fix for it at the examples. Looks like the issue is related to the ` ` at the end of the token. Didn't noticed before.

**Comment by freak4pc** [comment]
Ah interesting ! Definitely a bug though, the space shouldn’t matter.

Will have it fixed later today. Thanks for the feedback and glad to hear it’s working well for you so far 🦄

**Comment by freak4pc** [comment]
See #21
