### ISSUE TITLE
Styleguide Trees

### ISSUE THREAD

**Issue by gdelmas** [GettEngineering/Prism#23]
Are there plans to support Zeplin Global Styleguides and Styleguide trees with parent‑child relationships?

**Comment by freak4pc** [comment]
We are supporting child/ancestor styleguides.
If you have a project ID which uses a styleguide (for example "iOS") which has two ancestors: "Mobile", "Base", Prism will pull Text Styles and Colors of the entire tree.

**Comment by gdelmas** [comment]
that is great, i was not expecting it as i get this output (and than the command fails as per other issue).

```
⏳ Getting your projects ...
🔎 Found 4 projects:
  1) 🌐 MX Web — AAA (0 colors, 0 text styles)
  2) 🌐 MX Web — III (0 colors, 0 text styles)
```

**Comment by freak4pc** [comment]
@gdelmas Yeah actually this is a Zeplin API error. I might remove these counts because the count in the API doesn't reflect ancestors. 

Closing this for now :) Thanks!
