### ISSUE TITLE
HTTP 404 during `prism generate`

### ISSUE THREAD

**Issue by forsan** [GettEngineering/Prism#24]
Thank you for the amazing tools!!

I face the error below if I use the first project, any other project working fine.
<img width="682" alt="Screen Shot 2020-05-23 at 8 32 43 AM" src="https://user-images.githubusercontent.com/1745621/82722529-5caa0b80-9cd0-11ea-995a-ef590ae4a722.png">

The first project related to the design system and it contains colors, style guides, and spacing.
<img width="1287" alt="Screen Shot 2020-05-23 at 8 37 59 AM" src="https://user-images.githubusercontent.com/1745621/82722669-713ad380-9cd1-11ea-86be-79f0719e6d80.png">

Appreciate your support

**Comment by freak4pc** [comment]
Hey @forsan ! Thank you :)

I've added some more verbose logging for that failure on `master`. Do you mind cloning the project and running from source like so:

```sh
swift run --package-path /path/to/clone prism generate
```

**Comment by forsan** [comment]
Thank you for the swift response :)

<img width="766" alt="Screen Shot 2020-05-23 at 10 10 35 PM" src="https://user-images.githubusercontent.com/1745621/82738689-4ccb0f80-9d42-11ea-8a8e-1c4fcb28f1bf.png">

**Comment by freak4pc** [comment]
Mind copy pasting the error instead of screenshot ? Would be easier to read :)

**Comment by forsan** [comment]
Sorry about that.

`❌ Error: An unknown HTTP 404 API error to https://api.zeplin.dev/v1/styleguides/5e4b66ed832f72b66719a8cb/colors?offset=0&limit=100 occured: keyNotFound(CodingKeys(stringValue: "detail", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"detail\", intValue: nil) (\"detail\").", underlyingError: nil))
An unknown HTTP 404 API error to https://api.zeplin.dev/v1/styleguides/5e4b66ed832f72b66719a8cb/spacing_tokens?offset=0&limit=100 occured: keyNotFound(CodingKeys(stringValue: "detail", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"detail\", intValue: nil) (\"detail\").", underlyingError: nil))
An unknown HTTP 404 API error to https://api.zeplin.dev/v1/styleguides/5e4b66ed832f72b66719a8cb/text_styles?offset=0&limit=100 occured: keyNotFound(CodingKeys(stringValue: "detail", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"detail\", intValue: nil) (\"detail\").", underlyingError: nil))
`

**Comment by freak4pc** [comment]
@forsan Any chance you can try hitting that API with your token?

You can do this here on the web as well: 

https://docs.zeplin.dev/reference#createstyleguidecolor

There is some error but my parsing of it is wrong, so it would be useful if you could paste the error you're getting :) 

Thank you!

**Comment by forsan** [comment]
Check please

Api
`  --url 'https://api.zeplin.dev/v1/styleguides/5e4b66ed832f72b66719a8cb/colors?limit=30&offset=0' 
`

Error 404
`{
"message":"Styleguide not found"
}`

**Comment by freak4pc** [comment]
Yeah I see. The fact you don't get a proper message is an issue (fixing it now). 

The reason you get the error is much harder to debug. The only thing I can offer is that you send me your token so I can debug it here and then you can revoke your token and create a new one. 

Let me know if that option makes sense to you (if yes you can send the token to freak4pc AT gmail dot com)

**Comment by freak4pc** [comment]
The error messaging should be fixed on 5309868

**Comment by forsan** [comment]
Thank you for your extreme support. the design team creates one style guides for ios project and the android project may be in the wrong way because I check many APIs and i can't retrieve the style guides or colors or anything.
the team unlinks the shared style guides and upload only for ios project and now it's working fine.

`  1) 📱 DS (iOS) (18 colors, 0 text styles)
`

**Comment by freak4pc** [comment]
Still very weird, the styleguides should be automatically fetched so if the ID causes an issue this is either on my side or Zeplin's side... 

If you could take the time to possibly create some fake project with that scenario I'd really love to debug it. 

Happy it works for you for now! Can I close this issue ?

**Comment by forsan** [comment]
I'm sure it's from Zeplin because I try their APIs dashboard and not working with me.
Sure, I will prepare the project ASAP and update you.

I have 2 questions if you allow me.
1. I read in your website you are working on generate components, any expected date?
2. and I saw on your swift Heros talk, you use GitHub to let the designer push the changes, and in our case we are using Bitbucket on-premise.
So we can link our Bitbucket to a prism?

Sorry, I take a lot of time from you.

**Comment by freak4pc** [comment]
First about the issues - I also reached out to my friends at Zeplin so they can look into it, but if you make the project that would help a ton. Thank you!

About your questions:

Question 1 -  Can't commit to any date unfortunately, it's a long experimental process :) 

About your second question - You're not limited to GitHub or any other provider, since it's just a CLI tool you can run it as part of your CI to push the changes which is what we do. If you want to learn a bit more 

I did a talk on Bitrise's meetup which outlines our personal automation process, so that might help you gain some inspiration around that: https://youtu.be/SI8rQp8HaQU?t=5520 (Starts at 1h32m).

**Comment by freak4pc** [comment]
Hey @forsan - 
Is there any chance you can share the e-mail address / Zeplin user you use for your token? @forsan

**Comment by baguio** [comment]
Can confirm i am seeing the same error message ( `Styleguide not found` )

**Comment by freak4pc** [comment]
Hey @baguio - I'm happy to look into ths for you, can you tell me your Zeplin email / username so I can ask my friends at the Zeplin API team? Thanks!

**Comment by freak4pc** [comment]
Thanks for the debugging info @baguio. This will be fixed in 0.4.1, I'll release it later today (Fixed in #37)
