### ISSUE TITLE
Text Style "properties" not exposed as tokens or missing

### ISSUE THREAD

**Issue by gdelmas** [GettEngineering/Prism#26]
Thanks @freak4pc for making it possible to test Prism on our project without text style colors. I really like the simplicity of it.

I notices the following font styles are not exposed as tokens:

- `font_weight`
- `font_style`
- `font_stretch`

all but the last one are in the [model](https://github.com/GettEngineering/Prism/blob/master/Sources/ZeplinAPI/Models/TextStyle.swift#L30) and apparently not even optional in the [API](https://docs.zeplin.dev/reference#text_style).

**Comment by freak4pc** [comment]
Sure, I can definitely add those.

**Comment by freak4pc** [comment]
These are on `master`, let me know if that works for you :)

**Comment by gdelmas** [comment]
lovely, thank you so much. impressive turnaround.
