### ISSUE TITLE
Support line spacing

### ISSUE THREAD

**Issue by crysxd** [GettEngineering/Prism#41]
Hi! Thanks for this super helpful tool!

I'm currently building templates for an Android app. In Zeplin the line height is defined for some of our text styles (e.g. 18.2) with a text size of e.g. 15. To configure this in Android we need to have the "line spacing extra" being 3.2 in this example (18.2 - 15).

It would be great to do something like `{{% textStyle.lineHeight - textStyle.fontSize  %}}` or a similar syntax.

**Comment by freak4pc** [comment]
Hey, thank you very much! :)
Always exciting hearing of more people using Prism.

I think it would be non-trivial (and mostly useless for other cases) to support math as a whole, but — I believe we can easily add `textStyle.lineSpacing` instead, which prism will internally compute for you.

WDYT?

**Comment by crysxd** [comment]
That would be amazing! Simple workaround
